<script src="<?= base_url('assets/css/bootsrap/js/bootstrap.bundle.min.js') ?>"></script>
<script src='<?= base_url('node_modules/axios/dist/axios.js') ?>'></script>
<script src='<?= base_url('node_modules/chart.js/dist/chart.umd.js') ?>'></script>
<script src="<?= base_url('datatables/jQuery-3.7.0/jquery-3.7.0.min.js') ?>"></script>
<script src="<?= base_url('datatables/JSZip-3.10.1/jszip.min.js') ?>"></script>
<script src="<?= base_url('datatables/pdfmake-0.2.7/pdfmake.min.js') ?>"></script>
<script src="<?= base_url('datatables/pdfmake-0.2.7/vfs_fonts.js') ?>"></script>
<script src="<?= base_url('datatables/DataTables-1.13.5/js/jquery.dataTables.min.js') ?>"></script>
<script src="<?= base_url('datatables/DataTables-1.13.5/js/dataTables.bootstrap5.min.js') ?>"></script>
<script src="<?= base_url('datatables/Buttons-2.4.1/js/dataTables.buttons.min.js') ?>"></script>
<script src="<?= base_url('datatables/Buttons-2.4.1/js/buttons.bootstrap5.min.js') ?>"></script>
<script src="<?= base_url('datatables/Buttons-2.4.1/js/buttons.html5.min.js') ?>"></script>
<script src="<?= base_url('datatables/Buttons-2.4.1/js/buttons.print.min.js') ?>"></script>
<script src="<?= base_url('datatables/Responsive-2.5.0/js/dataTables.responsive.min.js') ?>"></script>
<script src="<?= base_url('datatables/Responsive-2.5.0/js/responsive.bootstrap5.js') ?>"></script>